[package]
name = "parsql-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.90"
quote = "1.0.37"
proc-macro2 = "1.0.92"
regex = "1.11.1"

[features]
default = []
tokio-postgres = []
sqlite = []
postgres = []
